### ISSUE TITLE
Segfault in updateReferences

### ISSUE THREAD

**Issue by janstarke** [janstarke/rexgen#72]
Additional segfault info:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b5a8b3 in rexgen::IteratorContainer::updateReferences(rexgen::IteratorState&) () from /usr/local/lib/librexgen.so.2.1
Missing separate debuginfos, use: dnf debuginfo-install gmp-6.2.0-7.fc35.x86_64 ocl-icd-2.3.0-2.fc35.x86_64 openssl-libs-1.1.1l-2.fc35.x86_64 zlib-1.2.11-30.fc35.x86_64
(gdb) bt
#0  0x00007ffff7b5a8b3 in rexgen::IteratorContainer::updateReferences(rexgen::IteratorState&) () from /usr/local/lib/librexgen.so.2.1
#1  0x00007ffff7b60a84 in rexgen::TopIterator::TopIterator(std::shared_ptr<rexgen::Regex>&) () from /usr/local/lib/librexgen.so.2.1
#2  0x00007ffff7b61b85 in c_regex_iterator () from /usr/local/lib/librexgen.so.2.1
#3  0x00000000006feaec in do_regex_hybrid_crack (db=db@entry=0x201f9e0 <database>, regex=0x214fff8 "\\01[23]", base_word=0x7fffffffaa80 "123456", regex_case=<optimized out>, regex_alpha=0x0) at regex.c:233
#4  0x00000000006e0155 in do_wordlist_crack (db=db@entry=0x201f9e0 <database>, name=<optimized out>, rules=0) at wordlist.c:1294
#5  0x00000000006b5979 in john_run () at john.c:1809
#6  main (argc=<optimized out>, argv=<optimized out>) at john.c:2082
(gdb) 
```

_Originally posted by @frank-dittrich in https://github.com/openwall/john/issues/4905#issuecomment-983364741_

**Comment by janstarke** [comment]
seems to be the same problem as in #71
